esphome:
  name: resource_status_example
  friendly_name: Resource Status Example

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

ota:
  password: "your_ota_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Resource Status Fallback"
    password: "your_fallback_password"

# Load our custom component from a Git repository
external_components:
  - source:
      type: git
      url: https://github.com/jappyjan/Attraccess-esphome-components.git # Repository URL
      ref: v0.0.3 # Optional: specify a branch, tag, or commit
    components: [attraccess_resource]

sensor:

# Configure our component
attraccess_resource:
  id: my_resource
  api_url: http://your-api-url.example.com # The component will automatically add "/api"
  resource_id: "12345"
  refresh_interval: 30s # Used for reconnect attempts if connection is lost, default 15s

# Add text sensor to show human-readable status
text_sensor:
  - platform: attraccess_resource
    resource: my_resource
    name: "Resource Status"
    id: resource_status

# Add binary sensors for resource monitoring
binary_sensor:
  # Monitor if API connection is available
  - platform: attraccess_resource
    resource: my_resource

    availability:
      name: "API Availability"
      id: api_availability

    in_use:
      name: "Resource In Use"
      id: resource_in_use
      on_press:
        - logger.log:
            level: INFO
            format: "The reosurce is in use, replace this with some automations"
      on_release:
        - logger.log:
            level: INFO
            format: "The resource is available, replace this with some automations"
