esphome:
  name: attraccess-test
  friendly_name: attraccess-test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
ota:
  - platform: esphome
    password: "c80ec2c641cf9cc7fb2ec53bbfec4485"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Attraccess-Test Fallback Hotspot"
    password: "mT24lkkKvQ3c"

captive_portal:

web_server:
  port: 80

# Define the main API Resource Status component
external_components:
  - source: components
    components: [attraccess_resource]

sensor:

# Configure the main component with an ID
attraccess_resource:
  id: attraccess_component
  api_url: http://192.168.178.183:3000
  resource_id: "1"
  refresh_interval: 30s

# Add text sensor to show human-readable status
text_sensor:
  - platform: attraccess_resource
    resource: attraccess_component
    name: "Resource Status"
    id: resource_status

# Add binary sensors for resource monitoring
binary_sensor:
  # Monitor if API connection is available
  - platform: attraccess_resource
    resource: attraccess_component
    availability:
      name: "API Availability"
      id: api_availability
    in_use:
      name: "Resource In Use"
      id: resource_in_use
      # This will be ON when device is in use, OFF when available
