esphome:
  name: attraccess-test
  friendly_name: attraccess-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG # Helpful for troubleshooting SSE connection

# Enable Home Assistant API
api:
  encryption:
    key: "zxt4TVpbKqt/iJ9SK0CxJ1I8WN1gUUolUOcSy41CtaY="

ota:
  password: "c80ec2c641cf9cc7fb2ec53bbfec4485"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Attraccess-Test Fallback Hotspot"
    password: "mT24lkkKvQ3c"

captive_portal:

# Define the main Attraccess Resource Status component
external_components:
  - source:
      type: git
      url: https://github.com/jappyjan/Attraccess-esphome-components.git
    components: [attraccess_resource]

# Configure the main component with an ID
attraccess_resource:
  id: attraccess_component
  api_url: http://localhost:3000
  resource_id: "1"
  refresh_interval: 30s

# Add text sensor to show human-readable status
text_sensor:
  - platform: attraccess_resource
    resource: attraccess_component
    name: "Resource Status"
    id: resource_status

# Configure binary sensors with the correct structure
binary_sensor:
  - platform: attraccess_resource
    resource: attraccess_component
    availability:
      name: "API Availability"
      id: api_availability
    in_use:
      name: "Resource In Use"
      id: resource_in_use
